steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/website-tools/mon-image-wordpress:1.0', '.' ]
- id: 'terraform init'
  name: 'hashicorp/terraform:1.0.0'
  script: terraform init
  dir: ./DevOps-Dauphine-TP
- id: 'terraform plan'
  name: 'hashicorp/terraform:1.0.0'
  script: terraform plan
  dir: ./DevOps-Dauphine-TP
- id: 'terraform apply'
  name: 'hashicorp/terraform:1.0.0'
  script: terraform apply --auto-approve
  dir: ./DevOps-Dauphine-TP
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/website-tools/mon-image-wordpress:1.0'
