steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/website-tools/mon-image-wordpress:1.0', '.' ]
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/website-tools/mon-image-wordpress:1.0'